# Generated by Django 3.2 on 2023-09-15 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_common_about_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='common',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/profiles'),
        ),
    ]
