# Generated by Django 3.2 on 2023-08-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hihglight',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
