# Generated by Django 3.2 on 2023-08-18 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_hihglight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='hihglight',
            new_name='highlight',
        ),
    ]
