# Generated by Django 3.2 on 2023-09-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolio_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image1',
            field=models.ImageField(upload_to='media/porfolio/%Y_%m_%d'),
        ),
    ]
